import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { diagnoseRepository } from "./diagnose.ts";
import type { RepoProfile } from "./types.ts";

/**
 * The diagnosis on a small synthetic repository whose facts are known: an npm
 * monorepo with tests, CI, generated code, one real secret and one
 * placeholder, docs, a Dockerfile and a short git history in which three
 * commits change the same three files together.
 */

const write = (root: string, rel: string, content: string) => {
  const abs = path.join(root, rel);
  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, content);
};

const git = (cwd: string, ...args: string[]) =>
  execFileSync("git", ["-c", "user.name=t", "-c", "user.email=t@x", "-c", "commit.gpgsign=false", ...args], { cwd, stdio: ["ignore", "pipe", "ignore"] });

function buildRepo(root: string) {
  write(root, "package.json", JSON.stringify({
    name: "synthetic", private: true, workspaces: ["packages/*"],
    scripts: { build: "tsc -b", test: "vitest run" },
    devDependencies: { vitest: "^3.0.0", eslint: "^9.0.0", typescript: "^5.0.0" },
  }, null, 2));
  write(root, "packages/a/package.json", JSON.stringify({ name: "@synthetic/a", dependencies: { react: "^19.0.0" } }, null, 2));
  write(root, "src/__generated__/x.ts", "export const x = 1;\n");
  write(root, "src/models.ts", "// <auto-generated>\n//     This code was generated by a tool.\n// </auto-generated>\nexport type Model = { id: string };\n");
  write(root, "src/a.ts", "export const a = 1;\n");
  write(root, "src/b.ts", "export const b = 1;\n");
  write(root, "src/c.ts", "export const c = 1;\n");
  write(root, "src/db.ts", [
    'export const live = "Server=db;Database=app;User Id=app;Password=Sup3rSecret;";',
    'export const local = "Server=localhost;Database=app;User Id=app;Password=changethis;";',
    "",
  ].join("\n"));
  write(root, "tests/x.test.ts", 'import { expect, it } from "vitest";\nit("works", () => expect(1).toBe(1));\n');
  write(root, ".github/workflows/ci.yml", "name: CI\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: npm test\n      - run: npm run build\n");
  write(root, ".env", "DB_HOST=localhost\n");
  write(root, "README.md", `# Synthetic\n\n${"Lorem ipsum dolor sit amet, consectetur adipiscing elit. ".repeat(160)}\n`);
  write(root, "docs/architecture.md", "# Architecture\n\nOne process, one database.\n");
  write(root, "Dockerfile", "FROM node:22\nCOPY . /app\n");
  write(root, ".eslintrc.json", "{}\n");

  git(root, "init", "-q");
  git(root, "add", "-A");
  git(root, "commit", "-q", "-m", "initial");
  for (const n of [1, 2, 3]) {
    for (const f of ["src/a.ts", "src/b.ts", "src/c.ts"]) write(root, f, `export const ${path.basename(f, ".ts")} = ${n + 1};\n`);
    git(root, "add", "-A");
    git(root, "commit", "-q", "-m", `change ${n}`);
  }
  write(root, "README.md", "# Synthetic\n\nRewritten.\n");
  git(root, "add", "-A");
  git(root, "commit", "-q", "-m", "readme");
  // The README on disk is the one the diagnosis measures; put the long one back after the history is made.
  write(root, "README.md", `# Synthetic\n\n${"Lorem ipsum dolor sit amet, consectetur adipiscing elit. ".repeat(160)}\n`);
}

describe("diagnoseRepository on a synthetic monorepo", () => {
  let root: string;
  let p: RepoProfile;

  beforeAll(async () => {
    root = mkdtempSync(path.join(os.tmpdir(), "dcc-diagnose-"));
    buildRepo(root);
    p = await diagnoseRepository(root, "synthetic");
  });
  afterAll(() => rmSync(root, { recursive: true, force: true }));

  it("names the repository and the walked files", () => {
    expect(p.name).toBe("synthetic");
    expect(p.path).toBe(root);
    expect(p.size.files).toBe(15);
    expect(p.size.top_level_dirs).toEqual([".github", "docs", "packages", "src", "tests"]);
    expect(p.size.bytes_on_disk_excl_git).toBeGreaterThan(9000);
  });

  it("sees TypeScript first, with its lines counted", () => {
    expect(p.languages[0]?.language).toBe("TypeScript");
    expect(p.languages[0]?.files).toBe(7);
    expect(p.languages[0]?.lines).toBeGreaterThan(0);
    expect(p.size.code_lines).toBe(p.languages[0]?.lines);
  });

  it("reads the manifests: frameworks, build, tests, lint", () => {
    expect(p.frameworks).toEqual(["eslint", "react (sub-package)", "typescript", "vitest"]);
    expect(p.build).toEqual({ system: ["package.json scripts"], commands: ["npm run build   # -> tsc -b"] });
    expect(p.tests).toEqual({ frameworks: ["package.json:test -> vitest run", "vitest"], test_files: 1, test_dirs: [["tests", 1]] });
    expect(p.lint_format).toEqual(["eslint", ".eslintrc.json"]);
    expect(p.package_managers).toEqual([]);
  });

  it("recognises the workspaces as a monorepo", () => {
    expect(p.monorepo.is_monorepo).toBe(true);
    expect(p.monorepo.workspaces).toEqual(["packages/*"]);
    expect(p.monorepo.packages).toEqual(["packages/a"]);
    expect(p.monorepo.package_count).toBe(1);
  });

  it("finds generated code by path and by header", () => {
    expect(p.generated_code.paths).toEqual([{ dir: "src/__generated__", files: 1 }]);
    expect(p.generated_code.header_marked_files).toBe(1);
    expect(p.generated_code.header_sample).toEqual(["src/models.ts"]);
    expect(p.generated_code.header_dirs).toEqual([{ dir: "src", files: 1 }]);
  });

  it("counts the real secret and not the placeholder, and lists the sensitive files", () => {
    expect(p.secrets.total).toBe(1);
    expect(p.secrets.outside_tests).toBe(1);
    expect(p.secrets.in_test_files).toBe(0);
    expect(p.secrets.by_kind).toEqual({ connection_string_with_password: 1 });
    expect(p.secrets.files).toEqual([{ path: "src/db.ts", hits: 1 }]);
    expect(p.secrets.sensitive_files).toContain(".env");
    expect(p.secrets.dotenv_examples).toEqual([]);
  });

  it("reads the CI workflow and its commands", () => {
    expect(p.ci.present).toBe(true);
    expect(p.ci.systems).toEqual(["github-actions"]);
    expect(p.ci.workflows).toEqual([{ file: ".github/workflows/ci.yml", name: "CI" }]);
    expect(p.ci.commands).toEqual(expect.arrayContaining(["npm test", "npm run build"]));
    expect(p.ci.workflow_count).toBe(1);
  });

  it("measures the docs and the environment", () => {
    expect(p.docs.readme).toBe("README.md");
    expect(p.docs.readme_bytes).toBeGreaterThanOrEqual(8000);
    expect(p.docs.docs_dir).toBe(true);
    expect(p.docs.architecture_docs).toContain("docs/architecture.md");
    expect(p.docs.license_kind).toBe("none");
    expect(p.docs.pr_template).toEqual([]);
    expect(p.docs.codeowners).toEqual([]);
    expect(p.environment.dockerfile).toEqual(["Dockerfile"]);
    expect(p.environment.docker_compose).toEqual([]);
    expect(p.external_systems).toHaveProperty("Docker");
    expect(p.ai_config).toEqual({ present: false, files: [], count: 0, kinds: [], sizes: {} });
    expect(p.windows_build.windows_only_build).toBe(false);
  });

  it("reads the git history: the three files that always change together", () => {
    expect(p.git.available).toBe(true);
    expect(p.git.commits_in_clone).toBe(5);
    expect(p.git.commits_analyzed).toBe(5);
    expect(p.git.authors_in_clone).toBe(1);
    expect(p.git.shallow).toBe(false);
    expect(p.git.tracked_files).toBe(15);
    expect(p.git.repeated_change_shapes?.[0]).toEqual({ files: ["src/a.ts", "src/b.ts", "src/c.ts"], times: 3 });
    expect(p.git.cochange_pairs).toEqual([]);
    expect(p.git.hot_files?.[0]).toEqual({ path: "src/a.ts", changes: 4, authors: 1 });
    // a, b and c four times each, and the four other .ts files once
    expect(p.git.churn_by_ext?.[".ts"]).toBe(16);
  });
});

describe("diagnoseRepository without git", () => {
  const dirs: string[] = [];
  afterAll(() => { for (const d of dirs) rmSync(d, { recursive: true, force: true }); });

  it("leaves the history out when asked to", async () => {
    const root = mkdtempSync(path.join(os.tmpdir(), "dcc-diagnose-"));
    dirs.push(root);
    buildRepo(root);
    const p = await diagnoseRepository(root, "synthetic", { git: false });
    expect(p.git).toEqual({ available: false });
    expect(p.monorepo.is_monorepo).toBe(true);
  });

  it("skips a packages/ directory only when it is a NuGet cache", async () => {
    const root = mkdtempSync(path.join(os.tmpdir(), "dcc-diagnose-"));
    dirs.push(root);
    write(root, "App.sln", "");
    write(root, "src/App/App.csproj", '<Project ToolsVersion="15.0"><PropertyGroup><TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion></PropertyGroup></Project>');
    write(root, "src/App/Program.cs", "class Program { }\n");
    write(root, "packages/Newtonsoft.Json.13.0.1/Newtonsoft.Json.13.0.1.nupkg", "");
    write(root, "packages/Newtonsoft.Json.13.0.1/lib/net45/Newtonsoft.Json.dll", "");
    const p = await diagnoseRepository(root, "dotnet", { git: false });
    expect(p.size.top_level_dirs).toEqual(["src"]);
    expect(p.size.files).toBe(3);
    expect(p.windows_build.legacy_netframework).toBe(true);
    expect(p.build.commands).toEqual(["msbuild App.sln /t:Build   # requires Windows / Visual Studio build tools"]);
  });
});

describe("an npm monorepo's packages/ is code, not a cache", () => {
  it("counts NuGet layouts under packages/ and nothing else", async () => {
    const { diagnoseRepository } = await import("./diagnose.ts");
    const { mkdtempSync, mkdirSync, writeFileSync, rmSync } = await import("node:fs");
    const { execFileSync } = await import("node:child_process");
    const os = await import("node:os");
    const path = await import("node:path");
    const root = mkdtempSync(path.join(os.tmpdir(), "dcc-diag-pk-"));
    try {
      mkdirSync(path.join(root, "packages/core/src"), { recursive: true });
      writeFileSync(path.join(root, "packages/core/src/a.ts"), "export const a = 1;\n");
      writeFileSync(path.join(root, "packages/core/package.json"), "{}");
      mkdirSync(path.join(root, "vendor/x"), { recursive: true });
      writeFileSync(path.join(root, "vendor/x/y.js"), "");
      const g = (...a: string[]) => execFileSync("git", ["-c", "user.name=t", "-c", "user.email=t@x", ...a], { cwd: root, stdio: "ignore" });
      g("init", "-q"); g("add", "-A"); g("commit", "-q", "-m", "x");
      const p = await diagnoseRepository(root, "pk");
      expect(p.git.tracked_package_dirs).toBe(1);
      expect(p.git.tracked_files).toBe(3);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
