import type { Concept } from "../index.ts";

/**
 * Repository onboarding as a coach (`openspec/changes/repository-coach`): the
 * dossier of a repository — the seven steps, the profile, the processes, the
 * trial run, the component cards, the build, the delivery, and the coach.
 * One entry per concept; the screen and the chat read the same words.
 */
export const ONBOARDING_CONCEPTS: Concept[] = [
  /* the steps */
  { key: "step_connect", kind: "section", title: "חיבור הריפו", aliases: ["חיבור", "connect", "עותק מבודד"], screens: ["onboarding"], explain: "DCC מושך את המאגר ופותח ענף משלו (ai/onboarding/<הרצה>) על עותק מבודד. שום דבר לא נכתב למאגר שלכם, ושום קריאה למודל לא נעשית." },
  { key: "step_diagnose", kind: "section", title: "אבחון", aliases: ["diagnose", "פרופיל", "מה מצאנו"], screens: ["onboarding"], explain: "סקריפט אחד, ללא מודל וללא עלות, קורא את הקוד וההיסטוריה ומפיק פרופיל: שפות, build, בדיקות, CI, קוד מג'ונרט, סודות (מיקום בלבד), מערכות חיצוניות, תיעוד. כל רכיב שיוצע אחר כך מצביע על עובדה מכאן." },
  { key: "step_processes", kind: "section", title: "תהליכים וראיון", aliases: ["תהליכים", "ראיון", "processes", "מבחן הסוכן"], screens: ["onboarding"], explain: "איך עובדים במאגר הזה: DCC אוסף ראיות (היסטוריה, CI, CONTRIBUTING, תבנית PR), שואל עד ארבע שאלות עם ברירת מחדל, וקלוד מפרק כל תהליך לצעדים. לכל צעד נערך מבחן הסוכן שמכריע: סוכן, skill או כלום." },
  { key: "step_trial", kind: "section", title: "ריצת ניסיון", aliases: ["ניסיון", "trial", "baseline", "נקודת התחלה"], screens: ["onboarding"], explain: "שלוש עד חמש משימות ייצוגיות רצות ב-Claude Code בלי שום רכיב, בקריאה בלבד, כדי לדעת מה הוא מצליח כאן לבד. זו נקודת ההתחלה שכל רכיב נמדד מולה; כל כישלון אומר איזה סוג רכיב חסר." },
  { key: "step_plan", kind: "section", title: "תוכנית הרכיבים", aliases: ["תוכנית", "כרטיסים", "plan", "רכיבים"], screens: ["onboarding"], explain: "כל רכיב שמוצע למאגר הזה, ככרטיס עם הראיה שהצדיקה אותו: כללי ההחלטה על הפרופיל, הכישלונות בניסיון, מבחן הסוכן, חיפוש רכיבים מוכנים, וסוקר נפרד. אתם מאשרים, שואלים או דוחים; שום דבר לא נכתב לפני כן." },
  { key: "step_build", kind: "section", title: "בנייה ואימות", aliases: ["בנייה", "אימות", "build", "verify"], screens: ["onboarding"], explain: "הרכיבים שאושרו נכתבים לענף המבודד לפי סוג בסדר תלות, וכל אחד מאומת בדרך שלו: hook נבדק בפעולה אסורה, הרשאה בפענוח, skill במבנה, מסמך בבדיקת נתיבים. ואז ריצת הניסיון שוב, לפני מול אחרי." },
  { key: "step_deliver", kind: "section", title: "מסירה", aliases: ["deliver", "PR", "בקשת מיזוג"], screens: ["onboarding"], explain: "commit של הקבצים המאושרים בלבד על שמכם, push לענף ו-PR עם דו\"ח שנכתב מהכרטיסים. המיזוג עצמו נשאר בידיים שלכם, באתר המארח." },
  { key: "step_kind", kind: "term", title: "סוג הצעד", aliases: ["דטרמיניסטי", "שער"], screens: ["onboarding"], explain: "דטרמיניסטי = DCC לבד, בלי מודל; AI = קלוד עושה חלק מהעבודה; שער = הצעד ממתין להחלטה שלכם." },
  { key: "step_progress", kind: "field", title: "התקדמות ההרצה", aliases: ["כמה צעדים הסתיימו"], screens: ["onboarding"], explain: "כמה מתוך שבעת הצעדים הסתיימו. צעד שממתין לכם מסומן; צעד שנכשל אפשר להריץ שוב מהכפתור שלו." },
  { key: "step_cost", kind: "field", title: "עלות הצעד", screens: ["onboarding"], explain: "כמה הוציא הצעד הזה לבדו, מיומן הקריאות של קלוד. סכום כל הצעדים הוא עלות ההרצה." },

  /* connect and automation */
  { key: "automation_level", kind: "term", title: "מדרגת האוטומציה", aliases: ["אוטומציה", "הפיך", "מחכה לאישור", "נעול"], screens: ["onboarding"], explain: "עד כמה ההרצה עושה בלי לשאול: 'הפיך = עושה ומדווח' בונה רכיב הפיך וזול ומדווח, ומשמעותי מחכה לאישור; 'הכול באישור' מחכה על כל רכיב; 'נעול' גם לא מריץ דבר שעולה כסף בלי אישור." },
  { key: "what_dcc_does", kind: "section", title: "מה DCC יעשה ומה לא", screens: ["onboarding"], explain: "יקרא את כל המאגר, יעבוד רק בענף משלו, ויציג כל רכיב לפני שהוא נכנס ל-PR. לא ייגע בענף הראשי, לא יריץ דבר מול הסביבות שלכם, ולא יקרא קבצים שיסומנו כסודיים." },
  { key: "run_identity", kind: "field", title: "מי אחראי", aliases: ["בשם מי"], screens: ["onboarding"], explain: "האדם שהתחיל את ההרצה. כל פעולה שיוצאת החוצה, commit ו-PR, נחתמת בשמו." },
  { key: "existing_ai_setup", kind: "field", title: "הגדרות AI קיימות", aliases: ["CLAUDE.md קיים"], screens: ["onboarding"], explain: "מה כבר יש במאגר בשביל Claude Code: CLAUDE.md, AGENTS.md, rules, skills, hooks, agents. ההטמעה מוסיפה רק מה שחסר ולא דורסת." },

  /* the profile */
  { key: "step_description", kind: "section", title: "תיאור השלב", screens: ["onboarding"], explain: "מה הצעד הזה עושה באופן כללי, וכל סוגי הרכיבים שהוא בעיקרון יכול להוביל אליהם — לא רק מה שנמצא במאגר הזה." },
  { key: "profile_card", kind: "section", title: "מה מצאנו", aliases: ["פרופיל הריפו"], screens: ["onboarding"], explain: "הפרופיל של המאגר כפי שהאבחון קרא אותו, עובדה-עובדה. עובדה שלא נכונה מסמנים ב'זה לא נכון', והכלל שנשען עליה לא יופעל." },
  { key: "fact_wrong", kind: "button", title: "זה לא נכון", aliases: ["תיקון עובדה", "correction"], screens: ["onboarding"], explain: "מסמן עובדה בפרופיל כלא נכונה, עם הערה אם רוצים. התיקון נרשם ביומן.", press: "הכללים שנשענים על העובדה הזאת לא יופעלו, והתוכנית מצוירת מחדש אם היא כבר פתוחה. הפרופיל עצמו לא משתנה — התיקון מוצג לצדו." },
  { key: "profile_languages", kind: "field", title: "שפות", screens: ["onboarding"], explain: "השפות שנמצאו במאגר לפי סיומות הקבצים, עם מספר הקבצים והשורות. מכאן נגזרים תוספי השפה (LSP) ומשימות הניסיון." },
  { key: "profile_frameworks", kind: "field", title: "מסגרות וספריות", screens: ["onboarding"], explain: "המסגרות והספריות שזוהו בקובצי ההגדרה (package.json, csproj, pom.xml ודומיהם). מכאן נגזר החיפוש אחר רכיבים מוכנים לסטאק." },
  { key: "profile_build", kind: "field", title: "build", screens: ["onboarding"], explain: "איך בונים את המאגר לפי מה שנמצא: מערכת ה-build והפקודה. אם לא נמצאה פקודה, הסוכן ינחש — ולכן זו עובדה שמקבלת רכיב." },
  { key: "profile_windows_only", kind: "field", title: "build רק ב-Windows", screens: ["onboarding"], explain: "המאגר נבנה רק ב-msbuild על Windows (‎.NET Framework, קובצי חתימה). בלי מריץ Windows אין build ואין בדיקות, וכל רכיב יסומן 'לא אומת כאן'." },
  { key: "profile_tests", kind: "field", title: "בדיקות", screens: ["onboarding"], explain: "מסגרת הבדיקות שנמצאה ומספר קובצי הבדיקה. בלי מסגרת, סוכן ש'מוסיף בדיקות' היה ממציא מסגרת — ולכן לא מוצע." },
  { key: "profile_lint", kind: "field", title: "lint ופורמט", screens: ["onboarding"], explain: "כלי הסגנון שמוגדרים במאגר. כשיש כזה, hook מריץ אותו על כל קובץ שנערך; כשאין, hook פורמט היה מפרמט קבצים שאיש לא פרמט." },
  { key: "profile_ci", kind: "field", title: "CI", screens: ["onboarding"], explain: "האם יש אינטגרציה רציפה ומה היא מריצה. ה-CI מגדיר מה 'ירוק'; בלעדיו נבנה שער מקומי." },
  { key: "profile_monorepo", kind: "field", title: "מבנה", screens: ["onboarding"], explain: "האם המאגר מחזיק חבילה אחת או הרבה. במאגר רב-חבילות קובץ הנחיות אחד בשורש לא יכול לתת את הפקודה הנכונה לכל חבילה." },
  { key: "profile_generated", kind: "field", title: "קוד מג'ונרט", screens: ["onboarding"], explain: "קבצים שמיוצרים אוטומטית (לפי נתיב או כותרת). עריכה ידנית שלהם נדרסת ב-build הבא, ולכן hook חוסם אותה." },
  { key: "profile_secrets", kind: "field", title: "סודות", screens: ["onboarding"], explain: "מחרוזות בצורת סוד וקבצים רגישים לפי השם. DCC רושם רק מיקום, לעולם לא ערך. הסוכן יקבל איסור קריאה עליהם, וסודות אמיתיים מדווחים לבעלים." },
  { key: "profile_external", kind: "field", title: "מערכות חיצוניות", screens: ["onboarding"], explain: "מסדי נתונים, Dataverse, ענן, מערכות ניהול משימות שהקוד פונה אליהן. הסכמה שלהן חיה מחוץ למאגר, ולכן חיבור MCP או כלל 'לא לנחש שמות'." },
  { key: "profile_ai_config", kind: "field", title: "הגדרות AI קיימות", screens: ["onboarding"], explain: "קובצי הנחיה שכבר יש: CLAUDE.md, AGENTS.md, Cursor, Copilot. כשיש, ההטמעה מוסיפה רק דלתא; כשיש כמה שסותרים, מוצע מיזוג לאחד." },
  { key: "profile_docs", kind: "field", title: "תיעוד", screens: ["onboarding"], explain: "README, תיקיית docs, מסמכי ארכיטקטורה, CONTRIBUTING, תבנית PR. תיעוד עשיר = שורת 'קרא קודם'; תיעוד דל = מסמכים מהאבחון." },
  { key: "profile_environment", kind: "field", title: "סביבה", screens: ["onboarding"], explain: "devcontainer, Dockerfile, compose, Makefile. סביבה משוחזרת שכבר קיימת היא המקום להריץ בו את הסוכן." },
  { key: "profile_history", kind: "field", title: "היסטוריית git", screens: ["onboarding"], explain: "כמה commits ומחברים, נקודות חמות (תיקיות שהרבה אנשים משנים הרבה) וצורות שינוי שחוזרות (אותם קבצים משתנים יחד). מכאן נגזרים skills של מתכון וסוקר לנקודה חמה." },
  { key: "profile_hygiene", kind: "field", title: "היגיינה", screens: ["onboarding"], explain: "בינאריים, מטמון חבילות וקובצי IDE שנמצאים בתוך git. הסוכן היה קורא אותם כקוד; הם מקבלים איסור קריאה ו-.gitignore." },
  { key: "profile_size", kind: "field", title: "גודל", screens: ["onboarding"], explain: "מספר הקבצים, שורות הקוד והנפח. משפיע על עלות ההקשר ועל הצורך בניווט מדויק (LSP)." },
  { key: "profile_license", kind: "field", title: "רישיון", screens: ["onboarding"], explain: "קובץ הרישיון של המאגר, אם יש. נרשם בפרופיל בלבד." },
  { key: "stack_tags", kind: "field", title: "תגיות סטאק", aliases: ["סטאק"], screens: ["onboarding"], explain: "מילות המפתח שנגזרו מהפרופיל (מערכות, מסגרות, מנהלי חבילות, שפות). לפיהן קלוד מחפש רכיבים מוכנים, והזיכרון מציע את מה שנמצא כבר למאגר הבא עם אותו סטאק." },

  /* processes and the interview */
  { key: "interview", kind: "section", title: "מה הקוד לא אומר", aliases: ["שאלות", "ראיון קצר"], screens: ["onboarding"], explain: "עד ארבע שאלות על מה שאי אפשר לדעת מהקוד: מי עובד עם AI, אזורים אסורים, מה נחשב 'גמור', האם יש מריץ. לכל שאלה ברירת מחדל; תשובה שלא ניתנה נרשמת כהנחה." },
  { key: "interview_assumed", kind: "term", title: "הנחה", aliases: ["assumed", "ברירת מחדל"], screens: ["onboarding"], explain: "שאלה שאיש לא ענה עליה: נלקחה ברירת המחדל והיא מסומנת כהנחה, כדי שיהיה ברור מה ידוע ומה הונח." },
  { key: "process_list", kind: "section", title: "מועמדים לסקילים ולסוכנים", aliases: ["תהליך", "התהליכים שנמצאו"], screens: ["onboarding"], explain: "סוגי השינוי החוזרים במאגר הזה (הוספת שדה, שחרור גרסה, עדכון תלויות) — כל אחד עם הראיה שהראתה אותו, מפורק לצעדים, וכל צעד נבדק אם הוא מועמד לסוכן, ל-skill, או לא צריך כלום מיוחד." },
  { key: "process_step", kind: "field", title: "שלב", screens: ["onboarding"], explain: "אחד השלבים שמרכיבים את התהליך שמעליו, בסדר שהם קורים במאגר הזה. לא אחד משבעת הצעדים של ההטמעה עצמה." },
  { key: "process_step_detail", kind: "field", title: "פירוט השלב", screens: ["onboarding"], explain: "מה קורה בצעד הזה בפועל במאגר, כפי שנמצא בקוד ובהיסטוריה." },
  { key: "agent_test", kind: "term", title: "מבחן הסוכן", aliases: ["חמש שאלות", "צריך סוכן"], screens: ["onboarding"], explain: "5 שאלות על כל שלב, שקובעות אם הוא צריך סוכן, skill, או לא צריך עזרה: שיפוט עצמאי? מידע או גישה חסרים? הרבה קריאה? ריצה במקביל? כבר נכשל בפועל? לחיצה על \"כן\" מראה מה הוא אומר בשלב הזה." },
  { key: "step_decision", kind: "field", title: "ההחלטה לשלב", aliases: ["סוכן / skill"], screens: ["onboarding"], explain: "מה השלב מקבל, ולמה: סוכן (עוזר נפרד עם שיפוט או גישה משלו), skill (נוהל כתוב שהסוכן הראשי עוקב אחריו), או אין צורך בסוכן או סקיל. נגזרת ממבחן הסוכן, לא נבחרת ידנית." },
  { key: "process_impossible", kind: "term", title: "אי אפשר כאן", aliases: ["impossible"], screens: ["onboarding"], explain: "תהליך שאי אפשר להריץ במכונה של DCC, למשל כי ה-build רץ רק ב-Windows. הוא נרשם עם הסיבה במקום להיעלם." },

  /* the trial */
  { key: "trial_tasks", kind: "section", title: "משימות הניסיון", aliases: ["המשימות"], screens: ["onboarding"], explain: "המשימות שנגזרו מהפרופיל ומהתהליכים: איך מריצים בדיקות, איך בונים, איפה מוסיפים, מה עושים עם קוד מג'ונרט. אותן משימות רצות שוב אחרי הבנייה." },
  { key: "trial_judge", kind: "term", title: "מי שופט", aliases: ["שופט", "judge"], screens: ["onboarding"], explain: "הקוד שופט כשאפשר לבדוק את התשובה מול הפרופיל (למשל טענה ש-build עבר במאגר שאי אפשר לבנות כאן). כשאי אפשר, מודל אחר מזה שביצע את המשימה שופט מול העובדות." },
  { key: "failure_kind", kind: "term", title: "סוג הכישלון", aliases: ["למה נכשל"], screens: ["onboarding"], explain: "לא ידע עובדה → שורת הנחיה; ידע ועבר על כלל → hook; חסר מידע חיצוני → MCP; לא יכול לאמת → סקריפט או מריץ; שיפוט שגוי → סוכן בודק. כך כישלון הופך לרכיב." },
  { key: "trial_estimate", kind: "field", title: "עלות משוערת", aliases: ["כמה תעלה הריצה"], screens: ["onboarding"], explain: "הערכה לפי מחירון המודל ומספר המשימות. העלות בפועל נרשמת ביומן הקריאות ומוצגת בעלות ההרצה." },
  { key: "trial_approve", kind: "button", title: "הרץ את הניסיון", aliases: ["אישור הניסיון"], screens: ["onboarding"], explain: "מריץ את משימות הניסיון ב-Claude Code, בקריאה בלבד, בעותק המבודד.", press: "עולה כסף לפי ההערכה. שום קובץ לא נכתב. התוצאה היא נקודת ההתחלה שהבנייה תימדד מולה." },
  { key: "trial_before_after", kind: "field", title: "לפני / אחרי", aliases: ["דלתא", "שיפור"], screens: ["onboarding"], explain: "כמה משימות עברו לפני הבנייה וכמה אחריה, ומה קרה לעלות למשימה. זו המדידה היחידה שאומרת אם הסט עזר; רכיב שלא שיפר מוצע להסרה." },

  /* the cards */
  { key: "component_card", kind: "term", title: "כרטיס רכיב", aliases: ["כרטיס", "רכיב"], screens: ["onboarding"], explain: "רכיב אחד שמוצע למאגר: למה (הראיה), מה הוא עושה, מקור, סיכון, עלות הקשר ואיך נבדוק. הכרטיס הוא מה שמאשרים — לא קובץ." },
  { key: "component_why", kind: "field", title: "כי ראיתי", aliases: ["הראיה"], screens: ["onboarding"], explain: "העובדה — מהפרופיל, מהניסיון, מהתהליך או מסריקת טיוטת /init — שהצדיקה את הרכיב. ריפו בלי העובדה הזאת לא היה מקבל את הרכיב." },
  { key: "component_kind", kind: "field", title: "סוג הרכיב", aliases: ["hook", "skill", "סוכן", "MCP", "הרשאה", "שורת הנחיה"], screens: ["onboarding"], explain: "שורת הנחיה מלמדת; hook אוכף; הרשאה מונעת; skill הוא נוהל; סוכן הוא עוזר נפרד; MCP הוא חיבור למערכת; מסמך הוא ידע; דיווח הוא מידע לבעלים; מריץ הוא דרישה מהלקוח." },
  { key: "component_family", kind: "field", title: "משפחה", aliases: ["בטיחות", "אימות", "ידע", "חיבורים"], screens: ["onboarding"], explain: "המשפחות הן סדר הבנייה: בטיחות, אימות, ידע, חיבורים, skills, סוכנים, אכיפה, מדידה. כל משפחה מקבלת החלטה כתובה בשער המוכנות." },
  { key: "component_source", kind: "field", title: "מקור", aliases: ["מאיפה זה בא"], screens: ["onboarding"], explain: "כלל החלטה (מספר הכלל), כישלון בניסיון, צעד בתהליך, חיפוש רכיבים מוכנים, הסוקר, טיוטת /init (דרך הסריקה), בקשה שלכם, או המאמן." },
  { key: "component_risk", kind: "field", title: "סיכון", aliases: ["הפיך", "משמעותי", "חיצוני"], screens: ["onboarding"], explain: "הפיך = קובץ שאפשר להסיר בלי נזק; משמעותי = משנה איך הסוכן עובד; חיצוני = נוגע במערכת מחוץ למאגר או דורש הרשאות. הסיכון קובע אם הרכיב נעשה לבד או מחכה לכם." },
  { key: "context_cost", kind: "field", title: "עלות הקשר", aliases: ["טוקנים בכל סשן"], screens: ["onboarding"], explain: "כמה טוקנים הרכיב מוסיף לכל סשן כשהוא נטען תמיד (שורת הנחיה, MCP עם כלים). רכיב יקר בהקשר צריך להצדיק את עצמו במדידה." },
  { key: "verify_how", kind: "field", title: "איך נבדוק", screens: ["onboarding"], explain: "המבחן של הרכיב הזה בבנייה: hook נבדק בפעולה אסורה, הרשאה בפענוח, skill במבנה, מסמך בנתיבים, סקריפט בהרצה. רכיב שלא ניתן לבדוק כאן אומר זאת." },
  { key: "group_auto", kind: "section", title: "נעשה ודווח", aliases: ["הפיך זול"], screens: ["onboarding"], explain: "רכיבים הפיכים וזולים שלא נוגעים בייצור. במדרגה 'הפיך = עושה ומדווח' הם נבנים בלי לשאול ומדווחים כאן; דיווחים לבעלים מופיעים כאן תמיד." },
  { key: "group_approval", kind: "section", title: "מחכה לאישורך", screens: ["onboarding"], explain: "רכיבים משמעותיים או שנוגעים במערכת חיצונית. כל אחד מחכה להחלטה: אשר, שאל בצ'אט, או דחה עם סיבה. אפשר לאשר את כולם כסט." },
  { key: "group_not_recommended", kind: "section", title: "לא מומלץ כאן", aliases: ["נדחה מראש"], screens: ["onboarding"], explain: "רכיבים שנשקלו ונדחו על ידי הכללים, עם הסיבה — כדי שתדעו מה נבדק. למשל סוכן בדיקות במאגר בלי מסגרת בדיקות." },
  { key: "card_approve", kind: "button", title: "אשר", screens: ["onboarding"], explain: "מאשר את הרכיב לבנייה.", press: "הרכיב ייבנה בענף המבודד בצעד הבנייה ויאומת. עדיין שום דבר לא יוצא מהמחשב — זה קורה רק במסירה." },
  { key: "card_decline", kind: "button", title: "דחה", screens: ["onboarding"], explain: "דוחה את הרכיב, עם סיבה שנרשמת ביומן ובדו\"ח ה-PR.", press: "הרכיב לא ייבנה. הסיבה מופיעה ב'לא התקנתי כי'. אפשר לבטל את ההחלטה כל עוד התוכנית פתוחה." },
  { key: "card_ask", kind: "button", title: "שאל", screens: ["onboarding"], explain: "פותח את הצ'אט על הכרטיס. הצ'אט עונה מהכרטיס עצמו בלי מודל; קריאת קוד היא קריאה נפרדת בעלות מוצהרת.", press: "נפתח הצ'אט עם השאלה על הרכיב. שום דבר לא משתנה בתוכנית." },
  { key: "approve_set", kind: "button", title: "אשר את כל מה שמחכה", aliases: ["אישור כסט"], screens: ["onboarding"], explain: "מאשר בבת אחת את כל הכרטיסים שמחכים לאישור.", press: "כל הכרטיסים שעוד לא הוכרעו מסומנים כמאושרים. הבנייה מתחילה רק מהכפתור שלה." },
  { key: "request_component", kind: "button", title: "בקש רכיב", aliases: ["תכין skill", "בקשה"], screens: ["onboarding"], explain: "מבקש רכיב שאינו בתוכנית, במילים שלכם: 'תכין skill לתהליך X'. קלוד הופך את זה לכרטיס עם עד שלוש שאלות.", press: "קריאה קצרה למודל (סנטים). נוצר כרטיס בקבוצת 'מחכה לאישורך' — הוא נבנה ומאומת כמו כל רכיב, ואתם מחליטים אם עזר." },
  { key: "card_questions", kind: "field", title: "שאלות הבהרה", screens: ["onboarding"], explain: "עד שלוש שאלות שהתשובה עליהן משנה מה נבנה, כל אחת עם ברירת מחדל. אפשר לאשר גם בלי לענות." },
  { key: "start_build", kind: "button", title: "בנה את מה שאושר", aliases: ["התחל בנייה"], screens: ["onboarding"], explain: "סוגר את התוכנית ומתחיל את הבנייה של הרכיבים המאושרים.", press: "הקבצים נכתבים לענף המבודד, כל רכיב מאומת, וריצת הניסיון רצה שוב (עולה כסף, מוצג). כרטיס שלא הוכרע נשאר בחוץ. שום דבר לא נדחף לפני המסירה." },
  { key: "draft_init", kind: "section", title: "טיוטת /init", aliases: ["init", "/init", "טרמינל"], screens: ["onboarding"], explain: "Claude Code האמיתי רץ בטרמינל בעותק המבודד עם /init, כמחולל טיוטה. מה שהוא כותב נכנס רק דרך כרטיס שאישרת אחרי סריקה; לפני הבנייה הטיוטה מוזזת הצידה ונשמרת." },
  { key: "draft_scan", kind: "button", title: "סרוק מה ש-/init עשה", aliases: ["סריקת הטיוטה", "סריקת init"], screens: ["onboarding"], explain: "עורך משווה את מה ש-/init כתב מול מה שהכרטיסים שלנו היו כותבים, ומחליט נושא אחר נושא: לקחת, לשלב, לבדוק, לשאול אותך או להשאיר בחוץ.", press: "קריאה אחת למודל החזק שקורא גם את הקוד כדי לבדוק טענות — כמה דקות, עולה כסף ונרשם בעלות הצעד. מה שהוא לוקח הופך לכרטיסים שמחכים לאישורך; שום דבר לא נכנס לבד." },
  { key: "draft_scan_result", kind: "section", title: "תוצאת הסריקה", aliases: ["מה הסריקה החליטה"], screens: ["onboarding"], explain: "מה העורך החליט על הטיוטה: ההכרעה הכללית, השוואה נושא אחר נושא, הכרטיסים שיצאו ממנה, מה משלנו מיותר ומה מהטיוטה לא נלקח ולמה." },
  { key: "draft_scan_verdict", kind: "term", title: "ההכרעה על הטיוטה", screens: ["onboarding"], explain: "אחת מארבע: הטיוטה טובה יותר ולוקחים את רובה; משלבים את שתיהן; שלנו הבסיס ורק תוספות מהטיוטה; או נשארים עם שלנו כי היא לא הוסיפה דבר נכון וספציפי." },
  { key: "draft_scan_compare", kind: "term", title: "השוואה נושא אחר נושא", screens: ["onboarding"], explain: "לכל נושא (build, מבנה, כללים…): מה אומר שלנו, מה אומרת הטיוטה, מי טוב יותר — והראיה לכך." },
  { key: "draft_scan_ask", kind: "term", title: "החלטה שרק אתה מקבל", aliases: ["שאלה מהסריקה"], screens: ["onboarding"], explain: "הסריקה מחליטה מה נכון לגבי הקוד, אבל לא מה מותר לסוכן — גישה לסביבה של הלקוח, פריסה, מדיניות. כרטיס כזה הוא שאלה: אישור הוא כן, דחייה היא לא." },
  { key: "card_text", kind: "field", title: "הנוסח", screens: ["onboarding"], explain: "הטקסט המדויק שייכתב אם תאשר את הכרטיס — בדיוק כך, בלי שינוי. כל נתיב ופקודה בו נבדקים מול הקוד בבנייה." },
  { key: "draft_start", kind: "button", title: "פתח סשן טיוטה", screens: ["onboarding"], explain: "פותח סשן Claude Code חי בטרמינל שלמטה עם /init.", press: "הסשן עולה כסף כל עוד הוא רץ, ונרשם ביומן. הקבצים שהוא כותב נשארים בענף המבודד כטיוטה; הם נכנסים ל-PR רק דרך רכיב מאושר." },
  { key: "readiness_gate", kind: "section", title: "שער המוכנות", aliases: ["מוכנות", "עשינו הכול?"], screens: ["onboarding"], explain: "ארבע שאלות שמכריעות אם ההטמעה מלאה: לכל תהליך ניסיון שעובר או 'אי אפשר כי'; לכל משפחה החלטה; הסוקר לא השאיר פער; הניסיון החוזר שיפר. מה שלא מתקיים נאמר במילים." },
  { key: "honesty_card", kind: "section", title: "כרטיס כנות", aliases: ["מה אי אפשר לאמת"], screens: ["onboarding"], explain: "מה אי אפשר לאמת במאגר הזה מהמכונה של DCC ומה צריך כדי שיהיה אפשר (למשל מריץ Windows), וכללים שלא הופעלו בגלל תיקון שלכם. נכנס גם לדו\"ח ה-PR." },
  { key: "rules_fired", kind: "field", title: "כללים שהופעלו", aliases: ["כללי ההחלטה"], screens: ["onboarding"], explain: "כללי ההחלטה שהאותות בפרופיל הפעילו, כל אחד עם הראיה. הכללים גלויים ואותם כללים רצים על כל מאגר; מה שמשתנה הוא הפרופיל." },
  { key: "marketplace_search", kind: "field", title: "חיפוש רכיבים מוכנים", aliases: ["marketplace", "plugins", "מקורות"], screens: ["onboarding"], explain: "קלוד חיפש ברשת plugins, שרתי MCP, ספריות skills ותוספי LSP לפי תגיות הסטאק. הקוד בדק אמון על כל מקור: יצרן, רישיון, פעילות, תיאורי כלים. מקור לא מאומת מוצג עם אזהרה ולעולם לא מותקן לבד; מקור שנמצא נזכר למאגר הבא." },
  { key: "source_trust", kind: "field", title: "אמון במקור", aliases: ["רשמי", "קהילה מוכרת", "לא מאומת"], screens: ["onboarding"], explain: "רשמי = היצרן של המערכת עצמה או Anthropic; קהילה מוכרת = ארגון ידוע עם רישיון ופעילות; לא מאומת = כל השאר. הדירוג הוא של הקוד, לא של המודל." },
  { key: "reviewer_pass", kind: "field", title: "הסוקר", aliases: ["מה חסר", "מה מיותר"], screens: ["onboarding"], explain: "קריאה נפרדת של קלוד שמקבלת את הפרופיל, התהליכים, הניסיון והרשימה, ושואלת רק מה חסר ומה מיותר. כל מה שהוא מעלה הופך לכרטיס לאישור; הוא לא מחליט." },

  /* the build */
  { key: "build_table", kind: "section", title: "מה נבנה ואיך אומת", aliases: ["טבלת האימות"], screens: ["onboarding"], explain: "כל רכיב שאושר: אילו קבצים נכתבו לו, באיזה מבחן נבדק ומה יצא. 'לא נבדק כאן' הוא תשובה כנה, לא כישלון." },
  { key: "validation_result", kind: "field", title: "תוצאת האימות", aliases: ["עבר", "נכשל", "לא נבדק כאן"], screens: ["onboarding"], explain: "עבר = המבחן הצליח; נכשל = הרכיב נכתב אבל המבחן נפל, והוא לא יוצא במסירה עד תיקון; לא נבדק כאן = דורש סביבה או הרשאות של הלקוח." },
  { key: "joint_check", kind: "field", title: "בדיקה משותפת", aliases: ["כפילויות", "סתירות"], screens: ["onboarding"], explain: "אחרי שכל הרכיבים נכתבו: האם שני רכיבים כותבים אותו קובץ, האם איסור קריאה מסתיר קובץ שרכיב אחר צריך, וכמה הקשר נטען בכל סשן." },
  { key: "always_loaded_tokens", kind: "field", title: "הקשר שנטען בכל סשן", screens: ["onboarding"], explain: "כמה טוקנים CLAUDE.md, AGENTS.md, ה-rules וכלי ה-MCP מוסיפים לכל סשן במאגר. מעל כמה אלפים כדאי לגזום." },
  { key: "files_written", kind: "field", title: "קבצים שנכתבו", screens: ["onboarding"], explain: "הקבצים שהבנייה כתבה בענף המבודד. רק קבצים של רכיבים שאומתו נכנסים למסירה." },

  /* delivery */
  { key: "deliver_button", kind: "button", title: "מסור: commit, push ו-PR", aliases: ["מסירה", "פתח PR"], screens: ["onboarding"], explain: "עושה commit של הקבצים המאושרים על שמכם, דוחף את הענף ופותח בקשת מיזוג עם הדו\"ח.", press: "הענף יוצא לשרת ונפתחת בקשת מיזוג בשמכם. הענף הראשי לא משתנה עד שתמזגו. אי אפשר לבטל את ה-push, אבל אפשר לסגור את ה-PR." },
  { key: "pr_report", kind: "section", title: "הדו\"ח שב-PR", aliases: ["דוח", "התקנתי כי"], screens: ["onboarding"], explain: "נכתב מהכרטיסים, לא מניסוח חופשי: התקנתי X כי Y ונבדק כך; לא התקנתי W כי; לפני/אחרי; וכרטיס הכנות. מי שקורא את ה-PR מבין בלי לפתוח קבצים." },
  { key: "deliver_files", kind: "field", title: "מה ייכנס למסירה", screens: ["onboarding"], explain: "רשימת הקבצים שיעברו commit — רק של רכיבים שאושרו ואומתו. קבצים אחרים בעותק המבודד, כולל טיוטת /init שלא אושרה, נשארים בחוץ." },

  /* the rail */
  { key: "run_cost", kind: "field", title: "עלות ההרצה", aliases: ["עלות", "כמה עלה"], screens: ["onboarding"], explain: "כמה ההרצה עלתה עד עכשיו, מיומן הקריאות, לפי צעד. חלק שסשן הטיוטה הוציא ועדיין לא נרשם מסומן בנפרד." },
  { key: "decision_log", kind: "section", title: "יומן החלטות ואירועים", screens: ["onboarding"], explain: "כל מה שקרה בהרצה לפי הסדר: צעד שהתחיל או נכשל, עובדה שתוקנה, תשובה בראיון, משימת ניסיון, כרטיס שהוכרע, רכיב שנבנה. שום דבר לא נמחק." },
  { key: "previous_runs", kind: "section", title: "הרצות קודמות", screens: ["onboarding"], explain: "הטמעות קודמות של אותו מאגר והרצות של המאמן. אפשר לפתוח הרצה ישנה ולראות מה נעשה בה ומה עלתה." },
  { key: "onboarding_intro", kind: "section", title: "מכינים את Claude לריפו הזה", screens: ["onboarding"], explain: "המטרה: שמפתח שמקבל משימה במאגר הזה יקבל מההתחלה את מה שהוא צריך — ידע, אימות, הגנות — כשכל רכיב נכנס רק כשיש ראיה שהבעיה שלו קיימת כאן." },
  { key: "steps_overview", kind: "section", title: "מה יקרה, בשבעה צעדים", screens: ["onboarding"], explain: "סקירה של הצעדים לפי הסדר: מה כל אחד עושה, מה הוא עולה ומה אתם מחליטים בו. התהליך קבוע לכל מאגר; התוצאה שונה לכל מאגר." },
  { key: "fixed_layout", kind: "section", title: "מבנה קבוע בריפו", aliases: ["איפה זה יושב"], screens: ["onboarding"], explain: "כל מאגר שמוטמע מקבל אותו מבנה: AGENTS.md ו-CLAUDE.md דק שמפנה אליו, ‎.claude/ עם settings, rules, skills, agents ו-hooks, ‎.mcp.json, REVIEW.md, docs/, ותיקיית ‎.dcc/ עם הפרופיל והרכיבים. מה בתוכם — לפי המאגר." },

  /* the coach */
  { key: "coach_panel", kind: "section", title: "המאמן", aliases: ["coach", "מאמן"], screens: ["onboarding"], explain: "מה שממשיך אחרי ההרצה, מהעבודה האמיתית: בדיקות שנכשלות שוב, משימות שצריכות סבב שני, עלות שעולה, וחדש בעולם. כל הצעה עם ראיה ומדד; אף הצעה על אירוע בודד, ואף הפרעה באמצע משימה." },
  { key: "health_score", kind: "field", title: "בריאות AI", aliases: ["ציון בריאות"], screens: ["onboarding"], explain: "ציון 0–100 מהמדדים שיש להם נתונים: משימות שעברו בניסיון ראשון, סבבי פיתוח למשימה, עלות למשימה. חלון של 30 יום, עם מגמה מול 30 הימים שלפני." },
  { key: "first_pass_rate", kind: "field", title: "עברו בניסיון ראשון", screens: ["onboarding"], explain: "חלק המשימות שכל הבדיקות שלהן עברו בסבב הפיתוח הראשון. המדד החשוב ביותר של 'הסוכן עובד טוב כאן'." },
  { key: "reruns_per_task", kind: "field", title: "סבבים נוספים למשימה", screens: ["onboarding"], explain: "כמה סבבי פיתוח נוספים נדרשו למשימה בממוצע, מעבר לראשון. עומד במקום 'תיקוני אדם' עד שהסשנים ידווחו אותם." },
  { key: "cost_per_task", kind: "field", title: "עלות למשימה", screens: ["onboarding"], explain: "ממוצע עלות ה-AI למשימה שפותחה במאגר, מיומן הקריאות. עלייה חדה מצביעה על הקשר שנטען ולא משמש." },
  { key: "coach_proposals", kind: "section", title: "הצעות המאמן", aliases: ["הצעות"], screens: ["onboarding"], explain: "הוספה, שינוי או הסרה של רכיב, עם הראיה שהציתה אותה והמדד שייבדק אחר כך. אישור פותח הרצת מאמן קצרה שמיישמת אותה בענף משלה ומוסרת כ-PR." },
  { key: "proposal_approve", kind: "button", title: "אשר הצעה", screens: ["onboarding"], explain: "מאשר הצעה של המאמן.", press: "נפתחת הרצת מאמן: אבחון מחדש (חינם), בניית הרכיב בענף מבודד, אימות, ומסירה כ-PR שממתין לכם. שום דבר לא נכתב לענף הראשי." },
  { key: "new_in_world", kind: "section", title: "חדש בעולם", screens: ["onboarding"], explain: "מקורות של רכיבים מוכנים שהשתנו מאז ההרצה האחרונה ומתאימים לסטאק של המאגר. DCC בודק אותם מחדש פעם בשבוע, כולל סריקה של תיאורי הכלים." },
  { key: "across_repos", kind: "section", title: "מה עבד במאגרים אחרים", aliases: ["למידה בין ריפואים"], screens: ["onboarding"], explain: "בכמה מאגרים כל רכיב אומת, ובכמה מהם הניסיון החוזר השתפר. מספרים מצטברים בלבד, בלי תוכן של אף לקוח." },
  { key: "installed_components", kind: "section", title: "מה מותקן במאגר", screens: ["onboarding"], explain: "הרכיבים שאומתו בהרצות שהושלמו, עם עלות ההקשר של כל אחד — המועמדים להסרה כשמדד מתדרדר." },
];
