import { execFileSync } from "node:child_process";
import { unlinkSync, writeFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import os from "node:os";
import path from "node:path";
import { git, httpsRepoUrl } from "../../ai-assist.ts";
import { ONBOARDING_METHODOLOGY_VERSION } from "../onboarding-version.ts";
import { registerStage } from "../state-machine.ts";
import type { StageOutcome } from "../types.ts";
import type { GenerateResult } from "./generate.ts";
import type { PlanResult } from "./plan.ts";
import type { ScanResult } from "./scan.ts";
import type { ValidateResult } from "./validate.ts";

/**
 * Stage 9 — Deliver. Push the onboarding branch, open the pull request,
 * then wait on the one thing DCC never does itself: the merge. Re-entered
 * on demand ("check again") until `merge-base --is-ancestor` says the
 * branch is in the default branch, at which point the repository is AI
 * Ready at a specific commit and methodology version.
 *
 * Uses the operator's ambient `git`/`gh` credentials — every push and PR
 * is attributable to the person running DCC, never a shared token.
 */
const LONGPATHS = process.platform === "win32" ? ["-c", "core.longpaths=true"] : [];

export type DeliverResult = {
  branch: string; base: string; pushed: boolean; remote: string | null;
  prNumber: number | null; prUrl: string | null; compareUrl: string | null; createdViaGh: boolean;
  merged: boolean; mergedSha?: string; readinessDate?: string; onboardingVersion: string; analyzedCommitSha: string;
  checks: number; lastCheckedAt: string; localOnly: boolean;
};

/** The shared checkout a worktree belongs to (refs are shared, so branch
 *  names resolve in either; `symbolic-ref HEAD` only makes sense there). */
async function sharedRootOf(dir: string): Promise<string | null> {
  const common = await git(["rev-parse", "--path-format=absolute", "--git-common-dir"], dir);
  if (common.code !== 0) return null;
  const gitDir = common.out.trim();
  return path.basename(gitDir) === ".git" ? path.dirname(gitDir) : gitDir;
}
async function localDefaultBranch(dir: string): Promise<string | null> {
  const root = await sharedRootOf(dir);
  if (!root) return null;
  const head = await git(["symbolic-ref", "--short", "HEAD"], root);
  return head.code === 0 ? head.out.trim() || null : null;
}

function hasGh(): boolean {
  try { execFileSync("gh", ["--version"], { stdio: "ignore" }); return true; } catch { return false; }
}
function findExistingPr(cwd: string, branch: string): { number: number; url: string } | null {
  try {
    const out = execFileSync("gh", ["pr", "list", "--head", branch, "--json", "number,url,state", "--state", "all"], { cwd, encoding: "utf8" });
    const list = JSON.parse(out) as { number: number; url: string }[];
    return list[0] ?? null;
  } catch { return null; }
}

export function composePrBody(ctx: { priorResults: Record<string, unknown> }, baselineSha: string): string {
  const gen = ctx.priorResults.generate as GenerateResult | undefined;
  const val = ctx.priorResults.validate as ValidateResult | undefined;
  const plan = ctx.priorResults.plan as PlanResult | undefined;
  const lines = (gen?.artifacts ?? []).map((a) => `- \`${a.path}\` — ${a.action}${a.estimatedTokens ? ` (~${a.estimatedTokens} tokens${a.kind === "claude_md" ? ", loaded every session" : a.kind === "settings" || a.kind === "guardrail_hook" || a.kind === "dcc_hooks" ? ", zero context cost" : ", on demand"})` : ""}`);
  const notCreated = (plan?.notCreated ?? []).map((n) => `- ${n.kind}: ${n.reason_he}`);
  return [
    "## What this PR adds",
    "",
    ...(lines.length ? lines : ["- (no files)"]),
    "",
    "## Why",
    "",
    "Repository AI Enablement by DCC: a short always-loaded CLAUDE.md that points to on-demand knowledge skills, path-scoped rules where justified, Read-deny rules and deterministic guardrail hooks, and DCC's session-capture hooks. Every artifact justified its existence in the reviewed plan; nothing here duplicates what Claude can derive from the code.",
    "",
    "## Deliberately not created",
    "",
    ...(notCreated.length ? notCreated : ["- (nothing skipped)"]),
    "",
    "## Validation",
    "",
    `- Status: ${val?.status ?? "n/a"} · checks: ${val?.checks.filter((c) => c.status === "pass").length ?? 0} passed, ${val?.checks.filter((c) => c.status === "warn").length ?? 0} warnings, ${val?.checks.filter((c) => c.status === "fail").length ?? 0} failed`,
    `- Always-loaded context added: ~${val?.budget.alwaysLoadedTokens ?? "?"} tokens (estimate); on demand: ~${val?.budget.onDemandTokens ?? "?"} tokens`,
    `- AI review: ${val?.review?.overall_status ?? "not run"} (${val?.review?.issues.length ?? 0} issues)`,
    "",
    "## Metadata",
    "",
    `- Baseline commit: \`${baselineSha}\``,
    `- Onboarding methodology: ${ONBOARDING_METHODOLOGY_VERSION}`,
    "",
    "---",
    "🤖 Generated by DCC Repository AI Enablement",
  ].join("\n");
}

registerStage("deliver", async (ctx): Promise<StageOutcome> => {
  const scan = ctx.priorResults.scan as ScanResult | undefined;
  const own = ctx.ownResult as DeliverResult | undefined;
  if (!scan?.branchName) return { status: "Failed", errors: ["scan did not record the onboarding branch"] };
  const dir = ctx.workspaceDir;
  const branch = scan.branchName;
  const now = new Date().toISOString();

  // Re-entry: only check whether the branch has been merged.
  if (own?.pushed || own?.localOnly) {
    if (!own.localOnly) {
      const fetch = await git([...LONGPATHS, "fetch", "origin"], dir, { timeoutMs: 60_000 });
      if (fetch.code !== 0) return { status: "Failed", errors: [`git fetch נכשל: ${fetch.out.slice(0, 300)}`], result: own };
    }
    const localBase = own.localOnly ? (await localDefaultBranch(dir)) ?? own.base : own.base;
    const target = own.localOnly ? localBase : `origin/${own.base}`;
    const isAncestor = await git(["merge-base", "--is-ancestor", branch, target], dir);
    const checked: DeliverResult = { ...own, base: localBase, checks: (own.checks ?? 0) + 1, lastCheckedAt: now };
    if (isAncestor.code !== 0) {
      return { status: "AwaitingExternal", warnings: [own.localOnly ? `הענף ${branch} עדיין לא מוזג ל-${localBase} (repo מקומי ללא remote — מזגו ידנית)` : `ה-PR עדיין לא מוזג ל-${own.base}`], result: checked };
    }
    const mergedSha = (await git(["rev-parse", target], dir)).out.trim();
    return { status: "Completed", result: { ...checked, merged: true, mergedSha, readinessDate: now } };
  }

  const review = ctx.priorResults.review as { decision?: string } | undefined;
  if (review?.decision !== "approve") return { status: "Failed", errors: ["review has not been approved"] };

  // `git()` merges stderr into `out`, so a failed lookup must be read by
  // its exit code — "No such remote 'origin'" is not a remote URL.
  const remoteRes = await git(["remote", "get-url", "origin"], dir);
  const remote = remoteRes.code === 0 ? remoteRes.out.trim() || null : null;
  const headRef = await git(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"], dir);
  const baseRaw = headRef.code === 0 ? headRef.out.trim().replace(/^origin\//, "") : "";
  const base = baseRaw || (await localDefaultBranch(dir)) || "main";
  const analyzedCommitSha = ctx.baselineSha;
  const common: Omit<DeliverResult, "pushed" | "prNumber" | "prUrl" | "compareUrl" | "createdViaGh" | "localOnly"> = {
    branch, base, remote, merged: false, onboardingVersion: ONBOARDING_METHODOLOGY_VERSION, analyzedCommitSha, checks: 0, lastCheckedAt: now,
  };

  if (!remote) {
    // A repository registered by local path with no remote: the branch is
    // in the shared clone; merging it is a local git operation for a person.
    return {
      status: "AwaitingExternal",
      warnings: [`אין remote ל-repository — הענף ${branch} קיים מקומית; מזגו אותו ל-${base} ולחצו "בדוק שוב"`],
      result: { ...common, pushed: false, prNumber: null, prUrl: null, compareUrl: null, createdViaGh: false, localOnly: true },
    };
  }

  const push = await git([...LONGPATHS, "push", "-u", "origin", branch], dir, { timeoutMs: 120_000 });
  if (push.code !== 0) return { status: "Failed", errors: [`git push נכשל: ${push.out.slice(0, 400)}`] };
  const httpsBase = httpsRepoUrl(remote);
  const compareUrl = httpsBase ? `${httpsBase}/compare/${encodeURIComponent(base)}...${encodeURIComponent(branch)}?expand=1` : null;
  const ghAvailable = hasGh();
  const existing = ghAvailable ? findExistingPr(dir, branch) : null;
  if (existing) return { status: "AwaitingExternal", result: { ...common, pushed: true, prNumber: existing.number, prUrl: existing.url, compareUrl, createdViaGh: false, localOnly: false } };
  if (!ghAvailable) {
    return { status: "AwaitingExternal", warnings: ["gh CLI אינו זמין — הענף נדחף; פתחו Pull Request ידנית דרך הקישור"], result: { ...common, pushed: true, prNumber: null, prUrl: null, compareUrl, createdViaGh: false, localOnly: false } };
  }
  const bodyFile = path.join(os.tmpdir(), `dcc-pr-body-${randomUUID()}.md`);
  writeFileSync(bodyFile, composePrBody(ctx, ctx.baselineSha), "utf8");
  try {
    const out = execFileSync("gh", ["pr", "create", "--title", "DCC: Repository AI Enablement", "--body-file", bodyFile, "--base", base, "--head", branch], { cwd: dir, encoding: "utf8" }).toString();
    const prUrl = out.trim().split("\n").pop() ?? out.trim();
    const m = prUrl.match(/\/pull\/(\d+)/);
    return { status: "AwaitingExternal", result: { ...common, pushed: true, prNumber: m ? Number(m[1]) : null, prUrl, compareUrl, createdViaGh: true, localOnly: false } };
  } catch (e) {
    return { status: "AwaitingExternal", warnings: [`gh pr create נכשל (${String((e as Error).message).slice(0, 200)}) — הענף נדחף; פתחו Pull Request ידנית`], result: { ...common, pushed: true, prNumber: null, prUrl: null, compareUrl, createdViaGh: false, localOnly: false } };
  } finally {
    try { unlinkSync(bodyFile); } catch { /* best effort */ }
  }
});
