import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { eq } from "drizzle-orm";
import { db } from "@dcc/db";
import { repo } from "@dcc/db/schema";
import { markWritten } from "../artifacts.ts";
import { commitWorkspaceChanges } from "../commit.ts";
import { dccHookSpecs, materializeDccHooks } from "../dcc-hooks.ts";
import { getGuardrailDefinition, renderGuardrailScript, toHookSpec } from "../guardrails.ts";
import { ONBOARDING_METHODOLOGY_VERSION } from "../onboarding-version.ts";
import { getActiveOnboardingPrompt } from "../prompts.ts";
import { createClaudeCodeRunner, READ_ONLY_TOOLS } from "../runner.ts";
import { GENERATE_SCHEMA } from "../schemas.ts";
import { resolveEffectivePolicy } from "../security-profiles.ts";
import { buildClaudeSettings, mergeClaudeSettings, type ClaudeSettingsJson, type HookSpec } from "../settings-adapter.ts";
import { registerStage } from "../state-machine.ts";
import type { PlannedArtifact, StageOutcome } from "../types.ts";
import type { BoundariesResult } from "./boundaries.ts";
import type { ConfirmResult } from "./confirm.ts";
import type { DiscoveryResult } from "./discovery.ts";
import type { PlanResult } from "./plan.ts";
import type { ScanResult } from "./scan.ts";

/**
 * Stage 6 — Generate. One AI call drafts every approved prose artifact
 * and returns the CONTENT (it never writes: everything under `.claude/` is
 * a protected path Claude Code won't auto-approve headless anyway, and a
 * write the model narrates but doesn't perform is exactly the silent
 * failure v1 kept hitting). DCC writes the files, stamps provenance,
 * materialises the deterministic artifacts, and commits — so the diff the
 * reviewer sees is exactly what DCC did.
 */
type GenFile = { key: string; path: string; content: string; notes_he?: string };
type GenOutput = { files: GenFile[]; summary_he?: string; skipped?: { key: string; reason_he: string }[] };

export type GeneratedArtifact = { key: string; kind: string; path: string; action: string; writer: "ai" | "dcc"; lines: number; estimatedTokens: number; hash: string | null };
export type GenerateResult = {
  filesWritten: string[];
  commitSha: string | null;
  artifacts: GeneratedArtifact[];
  missing: { key: string; path: string; reason_he: string }[];
  summary_he?: string;
  claudeExecutionId?: string;
  reviewNoteApplied?: string | null;
};

const provenance = (baseline: string, runId: string) =>
  `<!-- Generated by DCC Repository AI Enablement ${ONBOARDING_METHODOLOGY_VERSION} · baseline ${baseline.slice(0, 12)} · run ${runId.slice(0, 8)} · ${new Date().toISOString().slice(0, 10)}. Edit freely — DCC detects manual edits on refresh and never overwrites them without review. -->`;

function splitFrontmatter(text: string): { fm: string | null; body: string } {
  const m = text.match(/^---\s*\n([\s\S]*?)\n---\s*\n?/);
  return m ? { fm: m[1]!, body: text.slice(m[0].length) } : { fm: null, body: text };
}
const yamlStr = (s: string) => JSON.stringify(s);

function finalizeContent(a: PlannedArtifact, raw: string, baseline: string, runId: string): string {
  const stamp = provenance(baseline, runId);
  let text = raw.replace(/\r\n/g, "\n").trim() + "\n";
  if (a.kind === "claude_md" || a.kind === "nested_claude_md" || a.kind === "agent") {
    // One stamp, at the top; a stamp the model copied from an existing file is dropped.
    text = text.replace(/<!-- Generated by DCC Repository AI Enablement[\s\S]*?-->\n?/g, "");
    if (a.kind === "agent") {
      const { fm, body } = splitFrontmatter(text);
      return fm ? `---\n${fm}\n---\n${stamp}\n${body}` : `${stamp}\n${text}`;
    }
    return `${stamp}\n${text}`;
  }
  if (a.kind === "rule") {
    const { body } = splitFrontmatter(text.replace(/<!-- Generated by DCC[\s\S]*?-->\n?/g, ""));
    const paths = (a.rulePaths ?? []).map((p) => `  - ${yamlStr(p)}`).join("\n");
    return `---\npaths:\n${paths}\n---\n${stamp}\n${body.trim()}\n`;
  }
  if (a.kind === "knowledge_skill" || a.kind === "workflow_skill") {
    const { body } = splitFrontmatter(text);
    const s = a.skill!;
    const lines = [`name: ${s.name}`, `description: ${yamlStr(s.description)}`];
    if (s.paths?.length) lines.push("paths:", ...s.paths.map((p) => `  - ${yamlStr(p)}`));
    if (s.disableModelInvocation) lines.push("disable-model-invocation: true");
    lines.push("metadata:", `  dcc-onboarding: ${yamlStr(`${ONBOARDING_METHODOLOGY_VERSION} baseline=${baseline.slice(0, 12)} run=${runId.slice(0, 8)}`)}`);
    return `---\n${lines.join("\n")}\n---\n${body.replace(/<!-- Generated by DCC[\s\S]*?-->\n?/g, "").trim()}\n`;
  }
  return text;
}

registerStage("generate", async (ctx): Promise<StageOutcome> => {
  const scan = ctx.priorResults.scan as ScanResult | undefined;
  const boundaries = ctx.priorResults.boundaries as BoundariesResult | undefined;
  const discovery = ctx.priorResults.discovery as DiscoveryResult | undefined;
  const confirm = ctx.priorResults.confirm as ConfirmResult | undefined;
  const plan = ctx.priorResults.plan as PlanResult | undefined;
  if (!scan || !boundaries?.approved || !discovery || !plan?.approved) return { status: "Failed", errors: ["the plan has not been approved"] };
  const [r] = await db.select({ name: repo.name }).from(repo).where(eq(repo.id, ctx.repoId)).limit(1);

  const approved = plan.approved.filter((a) => a.action !== "skip");
  const aiItems = approved.filter((a) => a.writer === "ai");
  const warnings: string[] = [];
  const missing: GenerateResult["missing"] = [];
  const written: { key: string; path: string; action: string }[] = [];
  let claudeExecutionId: string | undefined;
  let summary_he: string | undefined;

  if (aiItems.length > 0) {
    const prompt = await getActiveOnboardingPrompt("onboarding.v2.generate");
    if (!prompt) return { status: "Failed", errors: ["no active prompt for onboarding.v2.generate — run seed-prompts.ts"] };
    const spec = aiItems.map((a) => ({
      key: a.key, kind: a.kind, path: a.path, action: a.action, justification: a.justification,
      ...(a.skill ? { skill: { name: a.skill.name, description: a.skill.description, paths: a.skill.paths ?? [] } } : {}),
      ...(a.rulePaths ? { rule_paths: a.rulePaths } : {}),
      max_lines: a.kind === "claude_md" ? 120 : a.kind === "nested_claude_md" ? 60 : a.kind === "rule" ? 60 : 150,
    }));
    const humanKnowledge = JSON.stringify({
      answers: (confirm?.answers ?? []).map((x) => ({ question: confirm?.questions.find((q) => q.id === x.id)?.question_he, answer: x.status === "answered" ? x.answer_he : "UNKNOWN" })),
      corrections: confirm?.corrections ?? null, notes: boundaries.approved.notes ?? null,
    });
    const runner = createClaudeCodeRunner();
    const exec = await runner.run({
      runId: ctx.runId, stageKey: "generate", repoId: ctx.repoId, clientId: ctx.clientId, cwd: ctx.workspaceDir,
      promptId: prompt.id, capability: "onboarding_generate", modelOverride: ctx.modelChoices.generate, tools: [...READ_ONLY_TOOLS], denyRules: boundaries.approved.rules,
      jsonSchema: GENERATE_SCHEMA as unknown as Record<string, unknown>,
      promptVars: {
        ARTIFACTS: JSON.stringify(spec),
        DISCOVERY: JSON.stringify(discovery.discovery),
        HUMAN_KNOWLEDGE: humanKnowledge,
        CLASSIFICATION: JSON.stringify(scan.classification ?? {}),
        REVIEW_NOTE: ctx.reviewNote?.trim() || "(none — first pass)",
        MODE: ctx.mode,
        AGENTS_MD: scan.inventory.summary.hasAgentsMd ? "AGENTS.md exists at the root: CLAUDE.md must start with `@AGENTS.md` and add only Claude-specific content below it." : "(no AGENTS.md)",
      },
      maxTurns: 70, timeoutMs: 1_200_000,
    });
    claudeExecutionId = exec.executionId;
    if (exec.status !== "Completed" || !exec.json) return { status: "Failed", errors: [exec.errorMessage ?? "generate call did not complete"], claudeExecutionId };
    const out = exec.json as GenOutput;
    summary_he = out.summary_he;
    for (const a of aiItems) {
      const f = (out.files ?? []).find((x) => x.key === a.key) ?? (out.files ?? []).find((x) => x.path?.replace(/^\.?\//, "") === a.path);
      if (!f || !f.content?.trim()) {
        const why = out.skipped?.find((s) => s.key === a.key)?.reason_he ?? "ה-AI לא החזיר תוכן לפריט הזה";
        missing.push({ key: a.key, path: a.path, reason_he: why });
        continue;
      }
      const full = path.join(ctx.workspaceDir, a.path);
      mkdirSync(path.dirname(full), { recursive: true });
      writeFileSync(full, finalizeContent(a, f.content, ctx.baselineSha, ctx.runId), "utf8");
      written.push({ key: a.key, path: a.path, action: a.action });
    }
    if (missing.some((m) => m.key === "claude_md")) return { status: "Failed", errors: ["ה-AI לא החזיר תוכן ל-CLAUDE.md — ניסיון חוזר נדרש"], claudeExecutionId, result: { missing } };
    for (const m of missing) warnings.push(`${m.path}: לא נוצר — ${m.reason_he}`);
  }

  // Deterministic artifacts: settings.json (merged when the team already has one), guardrails, DCC hooks.
  const hooks: HookSpec[] = [];
  for (const a of approved.filter((x) => x.kind === "guardrail_hook")) {
    const def = getGuardrailDefinition(a.catalogId ?? "");
    if (!def) continue;
    const full = path.join(ctx.workspaceDir, a.path);
    mkdirSync(path.dirname(full), { recursive: true });
    writeFileSync(full, renderGuardrailScript(def, plan.protectedGlobs), "utf8");
    hooks.push(toHookSpec(def));
    written.push({ key: a.key, path: a.path, action: a.action });
  }
  const dcc = approved.find((x) => x.kind === "dcc_hooks");
  if (dcc) {
    const files = materializeDccHooks(ctx.workspaceDir, { apiUrl: process.env.DCC_PUBLIC_API_URL ?? "http://localhost:3001", clientId: ctx.clientId, repoName: r?.name ?? "" });
    hooks.push(...dccHookSpecs());
    written.push({ key: dcc.key, path: dcc.path, action: dcc.action });
    void files;
  }
  const settings = approved.find((x) => x.kind === "settings");
  if (settings) {
    const generated = buildClaudeSettings(resolveEffectivePolicy(boundaries.approved.profileId, boundaries.approved.rules), hooks);
    const settingsPath = path.join(ctx.workspaceDir, ".claude", "settings.json");
    let final: ClaudeSettingsJson = generated;
    if (existsSync(settingsPath)) {
      try { final = mergeClaudeSettings(JSON.parse(readFileSync(settingsPath, "utf8")) as ClaudeSettingsJson, generated); }
      catch { warnings.push(".claude/settings.json הקיים לא ניתן לפענוח — נכתב מחדש (הגרסה הישנה נשמרת ב-git)"); }
    }
    mkdirSync(path.dirname(settingsPath), { recursive: true });
    writeFileSync(settingsPath, JSON.stringify(final, null, 2) + "\n", "utf8");
    written.push({ key: settings.key, path: settings.path, action: settings.action });
  }
  // A reviewer's per-file drop: remove and record.
  for (const a of plan.approved.filter((x) => x.action === "remove")) {
    const full = path.join(ctx.workspaceDir, a.path);
    if (existsSync(full)) rmSync(full, { recursive: true, force: true });
    written.push({ key: a.key, path: a.path, action: "remove" });
  }

  const { commitSha, filesChanged } = await commitWorkspaceChanges(ctx.workspaceDir, ctx.triggeredBy, ctx.mode === "refresh" ? "DCC: refresh AI enablement artifacts" : "DCC: repository AI enablement artifacts");
  const ledger = await markWritten(ctx.clientId, ctx.runId, ctx.workspaceDir, written);
  if (filesChanged.length === 0) warnings.push("לא נרשם שינוי ב-git — ייתכן שהתוכן זהה למה שכבר קיים בענף");

  const artifacts: GeneratedArtifact[] = written.map((w) => {
    const a = plan.approved!.find((x) => x.key === w.key)!;
    const l = ledger.find((x) => x.key === w.key);
    return { key: w.key, kind: a.kind, path: w.path, action: w.action, writer: a.writer, lines: l?.lines ?? 0, estimatedTokens: l?.estimatedTokens ?? 0, hash: l?.hash ?? null };
  });
  const result: GenerateResult = { filesWritten: filesChanged, commitSha, artifacts, missing, summary_he, claudeExecutionId, reviewNoteApplied: ctx.reviewNote ?? null };
  return { status: warnings.length ? "CompletedWithWarnings" : "Completed", warnings, claudeExecutionId, sourceCommitSha: commitSha ?? undefined, result };
});
