import { execFileSync } from "node:child_process";
import { writeFileSync, unlinkSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { git, httpsRepoUrl } from "../../ai-assist.ts";
import { ONBOARDING_METHODOLOGY_VERSION } from "../onboarding-version.ts";
import { registerStage } from "../state-machine.ts";
import type { StageOutcome } from "../types.ts";

/**
 * Stage 14 — GitHub Pull Request (spec §22). Only meaningfully reachable
 * after `user_review` approved. Deterministic, no Claude call. Uses
 * whatever `git`/`gh` credentials are already set up locally — same
 * "ambient, no per-user token" model `pushTask` (`ai-assist.ts`) already
 * uses for pushing task branches (Phase 1's decision 0.2), so every
 * GitHub action here is attributable to whoever is actually running DCC,
 * never a shared/stored credential. `gh` is treated as an ambient,
 * already-authenticated CLI the deployment provides — if it's missing
 * or fails, the stage still completes (push already succeeded) with a
 * compare URL for a human to open the PR manually, rather than hard-
 * failing the whole stage over an optional tool.
 */
const LONGPATHS = process.platform === "win32" ? ["-c", "core.longpaths=true"] : [];

function hasGh(): boolean {
  try {
    execFileSync("gh", ["--version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

type ExistingPr = { number: number; url: string; state: string };
function findExistingPr(cwd: string, branch: string): ExistingPr | null {
  try {
    const out = execFileSync("gh", ["pr", "list", "--head", branch, "--json", "number,url,state", "--state", "all"], { cwd, encoding: "utf8" });
    const list = JSON.parse(out) as ExistingPr[];
    return list[0] ?? null;
  } catch {
    return null;
  }
}

/** Exported for isolated verification — lets the PR text be checked
 *  without ever invoking `git push`/`gh pr create`. */
export function composeBody(ctx: { priorResults: Record<string, unknown> }, baselineSha: string): string {
  const knowledgeGen = ctx.priorResults.knowledge_generation as { filesWritten?: string[] } | undefined;
  const claudeMd = ctx.priorResults.claude_md_generation as { filesWritten?: string[] } | undefined;
  const doctor = ctx.priorResults.ai_doctor as { status?: string; rulesWritten?: string[] } | undefined;
  const guardrails = ctx.priorResults.guardrails as { approvedGuardrailIds?: string[] } | undefined;

  const generated = [
    ...(claudeMd?.filesWritten ?? []).map((f) => `- ${f}`),
    ...(knowledgeGen?.filesWritten ?? []).map((f) => `- ${f}`),
    ...(doctor?.rulesWritten ?? []).map((f) => `- ${f}`),
    "- .claude/settings.json",
    ...(guardrails?.approvedGuardrailIds ?? []).map((id) => `- .claude/hooks/${id}.mjs`),
  ];

  return [
    "## מה נוצר",
    "",
    ...generated,
    "",
    "## למה נוצר",
    "",
    "הכנה אוטומטית של הריפוזיטורי לעבודה עם Claude Code — ידע פרויקטלי, הגדרות הרשאה/אבטחה, וכללים ייעודיים, כפי שנקבע על ידי תהליך ה-onboarding.",
    "",
    "## תוצאת בדיקת תקינות (AI Doctor)",
    "",
    doctor?.status ?? "לא זמין",
    "",
    "## מטא-דאטה",
    "",
    `- Baseline commit: \`${baselineSha}\``,
    `- Onboarding methodology version: ${ONBOARDING_METHODOLOGY_VERSION}`,
    "",
    "---",
    "🤖 Generated by DCC Repository AI Enablement",
  ].join("\n");
}

registerStage("github_pull_request", async (ctx): Promise<StageOutcome> => {
  const review = ctx.priorResults.user_review as { decision?: string } | undefined;
  if (review?.decision !== "approve") return { status: "Failed", errors: ["user_review has not been approved"] };
  const workspaceSetup = ctx.priorResults.workspace_setup as { branchName?: string } | undefined;
  if (!workspaceSetup?.branchName) return { status: "Failed", errors: ["workspace_setup did not produce a branch name"] };
  const branch = workspaceSetup.branchName;
  const dir = ctx.workspaceDir;

  const ghAvailable = hasGh();
  const existing = ghAvailable ? findExistingPr(dir, branch) : null;

  const push = await git([...LONGPATHS, "push", "-u", "origin", branch], dir, { timeoutMs: 30_000 });
  if (push.code !== 0) return { status: "Failed", errors: [`git push נכשל: ${push.out.slice(0, 400)}`] };

  const remote = (await git(["remote", "get-url", "origin"], dir)).out;
  const base = (await git(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"], dir)).out.replace(/^origin\//, "") || "main";
  const httpsBase = httpsRepoUrl(remote);
  const compareUrl = httpsBase ? `${httpsBase}/compare/${encodeURIComponent(base)}...${encodeURIComponent(branch)}?expand=1` : undefined;

  if (existing) {
    return { status: "Completed", result: { prNumber: existing.number, prUrl: existing.url, pushed: true, createdViaGh: false, reused: true, compareUrl } };
  }

  if (!ghAvailable) {
    return {
      status: "CompletedWithWarnings",
      warnings: ["gh CLI אינו זמין — הענף נדחף אך יש לפתוח Pull Request ידנית"],
      result: { pushed: true, createdViaGh: false, compareUrl },
    };
  }

  const title = "DCC: הטמעת AI לריפוזיטורי";
  const body = composeBody(ctx, ctx.baselineSha);
  const bodyFile = path.join(os.tmpdir(), `dcc-pr-body-${randomUUID()}.md`);
  writeFileSync(bodyFile, body, "utf8");
  try {
    // `gh pr create` (unlike `gh pr view`/`gh pr list`) has no `--json`
    // support — it prints the created PR's URL as plain stdout text.
    const out = execFileSync("gh", ["pr", "create", "--title", title, "--body-file", bodyFile, "--base", base, "--head", branch], { cwd: dir, encoding: "utf8" }).toString();
    const prUrl = out.trim().split("\n").pop() ?? out.trim();
    const m = prUrl.match(/\/pull\/(\d+)/);
    const prNumber = m ? Number(m[1]) : null;
    return { status: "Completed", result: { prNumber, prUrl, pushed: true, createdViaGh: true, compareUrl } };
  } catch (e) {
    return {
      status: "CompletedWithWarnings",
      warnings: [`gh pr create נכשל (${String((e as Error).message).slice(0, 300)}) — הענף נדחף, יש לפתוח Pull Request ידנית`],
      result: { pushed: true, createdViaGh: false, compareUrl },
    };
  } finally {
    try { unlinkSync(bodyFile); } catch { /* best effort */ }
  }
});
