#!/usr/bin/env node
// DCC guardrail: Protect Secrets (PreToolUse, matcher "Read").
// Deterministic — no LLM call, no network access. Blocks reading files
// that look like secrets/credentials, regardless of any other approved
// read rule. Generated by DCC Repository AI Enablement onboarding —
// reviewed, static template, not repo-generated per run.
import { readFileSync } from "node:fs";

const input = JSON.parse(readFileSync(0, "utf8"));
const path = String(input?.tool_input?.file_path ?? "");

const SECRET_LIKE = /(^|[/\\])(\.env(\..*)?|.*\.pem|.*\.key|.*secrets?\.(json|ya?ml)|id_rsa|id_ed25519|.*\.pfx|.*credentials.*)$/i;

if (SECRET_LIKE.test(path)) {
  process.stderr.write(`DCC guardrail "Protect Secrets": refusing to read a secret-like path (${path}). If this is genuinely needed, a human must read it directly, not Claude.\n`);
  process.exit(2);
}
process.exit(0);
